"""empty message

Revision ID: 678a6dfe5633
Revises: 
Create Date: 2019-01-10 17:18:49.611160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678a6dfe5633'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_user',
    sa.Column('pk_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('login_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.Column('extra_resource', sa.VARCHAR(length=255), nullable=True),
    sa.Column('forbidden_resource', sa.VARCHAR(length=255), nullable=True),
    sa.Column('delete_flag', sa.INTEGER(), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('pk_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_user')
    # ### end Alembic commands ###
