"""empty message

Revision ID: b423b3935169
Revises: 678a6dfe5633
Create Date: 2019-01-10 17:21:52.355446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b423b3935169'
down_revision = '678a6dfe5633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_user', sa.Column('nick_name', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_user', 'nick_name')
    # ### end Alembic commands ###
